language: go

env:
  - CODECOV_TOKEN=f0e5aecb-ec50-4e36-acbf-2ccf154527db

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f0e5aecb-ec50-4e36-acbf-2ccf154527db
